name: Check price and notify

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-price:
    runs-on: ubuntu-latest
    env:
      ASSET1: "BANK"
      ASSET2: "ALGO"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: Install python modules
        run: pip install requests
      - name: Get asset data file
        run: curl https://api.algofi.org/assets | jq > assets.as
      - name: Notify
        env:
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "PRICE: $(python3 ./algoprice.py assets.as)"
          ls -la
      - name: create github pages
        env:
          GH_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: >
          gh repo clone msobolak/algo_bot
          && cd algo_bot
          && git checkout gh-pages
          && cp ../chart.html .
          && gh repo add chart.html
          && gh repo commit -m "Update $(date)"
          && gh repo push origin gh-pages
          
